name: eminent_news
description: A Flutter news application that consumes the Eminent News backend APIs

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # HTTP & API
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Routing
  go_router: ^13.0.0
  
  # UI Components
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  
  # Video Player
  video_player: ^2.8.2
  chewie: ^1.7.5
  
  # Utilities
  intl: ^0.19.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.3
  fluttertoast: ^8.2.4
  image_picker: ^1.0.7
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
